"""
EPA values generated by the ACT model.
"""

epa_sentences = {
    'SUBJECT':       [-0.54, 1.48, 1.48],   # subject of shouting at
    'OBJECT':       [0.54, -1.12, 1.47],    # object of shouting at
    'CONGRATULATE_S':   [2.23, 1.57, 1.22],
    'CONGRATULATE_O':   [1.67, 1.15, 1.13],
    'DISAGREE_WITH_S':  [0.66, 1.35, 1.32],
    'DISAGREE_WITH_O':  [1.13, 0.63, 1.08],
    'COMFORT_S':        [1.30, 1.25, 1.05],
    'COMFORT_O':        [-0.30, -0.81, -0.66],
    'CONSPIRE_WITH_S':  [0.43, 1.24, 1.23],
    'CONSPIRE_WITH_O':  [-0.55, 0.23, 0.46],
    'THREATEN_S':       [-2.06, 0.55, 1.11],
    'THREATEN_O':       [0.27, -1.63, -1.11],
    'RESCUE_S':         [0.03, 1.30, 1.03],
    'RESCUE_O':         [1.11, -1.17, 0.40]
}
